name: Build Windows wheels

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]

jobs:
  build-windows-wheels:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (3.9 for abi3)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install maturin
        run: python -m pip install --upgrade pip maturin

      - name: Build wheels
        working-directory: windows-capture-python
        run: |
          maturin build --release -o dist
          dir dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-capture-wheels
          path: windows-capture-python/dist/*.whl

      - name: Upload wheels to GitHub Release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-capture-python/dist/*.whl
            windows-capture-python/dist/*.tar.gz
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
